// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {tools} from '../models';
import {context} from '../models';
import {llm} from '../models';
import {http} from '../models';

export function AddKanbanCardMessage(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function AddWorkspace(arg1:string):Promise<services.AppState>;

export function AddWorkspaceFolder(arg1:string,arg2:string):Promise<services.AppState>;

export function AppInfo():Promise<services.AppInfo>;

export function CheckTokenBudget(arg1:string):Promise<boolean>;

export function ChooseWorkspaceFileSavePath(arg1:string,arg2:string):Promise<string>;

export function ChooseWorkspaceFolder():Promise<services.AppState>;

export function ChooseWorkspaceFolderForWorkspace(arg1:string):Promise<services.AppState>;

export function ChooseWorkspaceGitCloneParent():Promise<string>;

export function ChooseWorkspaceIcon(arg1:string):Promise<services.AppState>;

export function ClearChat(arg1:string):Promise<services.ChatSession>;

export function ClearDoneKanbanCards(arg1:string):Promise<services.KanbanBoard>;

export function ClearKanbanCardRecovery(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function ClearWorkspaceChangeReview(arg1:string):Promise<services.WorkspaceChangeReview>;

export function ClearWorkspaceIcon(arg1:string):Promise<services.AppState>;

export function CloneWorkspaceGitRepository(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.AppState>;

export function CloseKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function CommitWorkspaceGitChanges(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function CompleteWorkspaceFile(arg1:string,arg2:services.WorkspaceCompletionRequest):Promise<services.WorkspaceCompletionResponse>;

export function ContinueDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function CreateAgentMode(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<Array<services.AgentMode>>;

export function CreateAgentModeFromChat(arg1:string):Promise<tools.AgentModeCreationResult>;

export function CreateAgentModeFromChatProvider(arg1:string):Promise<tools.AgentModeCreationResult>;

export function CreateAgentModePerTool(arg1:string,arg2:string,arg3:Record<string, Array<string>>):Promise<Array<services.AgentMode>>;

export function CreateKanbanCardFromChatMessage(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function CreateKanbanCardFromTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<services.TaskKanbanConversion>;

export function CreateMode(arg1:context.Context,arg2:tools.AgentModeCreationRequest):Promise<tools.AgentModeCreationResult>;

export function CreateModePerTool(arg1:context.Context,arg2:string,arg3:string,arg4:Record<string, Array<string>>):Promise<tools.AgentModeCreationResult>;

export function CreateReadyKanbanCard(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<services.KanbanBoard>;

export function CreateSkillFromChat(arg1:string):Promise<services.WorkspaceSkillCreationResult>;

export function CreateWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFile>;

export function CreateWorkspaceFolder(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFileEntry>;

export function CreateWorkspaceGitBranch(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function CreateWorkspaceTask(arg1:string,arg2:services.TaskInput):Promise<services.TaskBoard>;

export function DeleteAgentMode(arg1:string):Promise<Array<services.AgentMode>>;

export function DeleteKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function DeleteWorkspace(arg1:string):Promise<services.AppState>;

export function DeleteWorkspacePaths(arg1:string,arg2:Array<string>):Promise<Array<services.WorkspaceDeletedPath>>;

export function DeleteWorkspaceTask(arg1:string,arg2:string,arg3:string):Promise<services.TaskBoard>;

export function DiscardWorkspaceGitChanges(arg1:string,arg2:string):Promise<services.WorkspaceGitRepositoryView>;

export function DiscardWorkspaceGitFile(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function EditChatMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.ChatSession>;

export function EnforceLiveness(arg1:string,arg2:services.LivenessConfig):Promise<void>;

export function EvaluateDebugExpression(arg1:string,arg2:services.DebugEvaluateRequest):Promise<services.DebugEvaluateResponse>;

export function ExecutePlan(arg1:string):Promise<services.KanbanBoard>;

export function FindWorkspaceFileDefinition(arg1:string,arg2:services.WorkspaceDefinitionRequest):Promise<services.WorkspaceDefinitionResponse>;

export function FindWorkspaceFileImplementations(arg1:string,arg2:services.WorkspaceReferenceRequest):Promise<services.WorkspaceReferenceResponse>;

export function FindWorkspaceFileReferences(arg1:string,arg2:services.WorkspaceReferenceRequest):Promise<services.WorkspaceReferenceResponse>;

export function GetDashboardLayouts():Promise<Record<string, Array<services.DashboardWidgetJSON>>>;

export function GetHeartbeatConfig(arg1:string):Promise<services.HeartbeatConfig>;

export function GetLivenessConfig(arg1:string):Promise<services.LivenessConfig>;

export function GetTokenBudget(arg1:string):Promise<services.TokenBudget>;

export function GetWatchdogConfig(arg1:string):Promise<services.WatchdogConfig>;

export function ListAgentModes(arg1:string):Promise<Array<services.AgentMode>>;

export function ListAgentModesProvider():Promise<Array<tools.AgentModeSummary>>;

export function ListModes():Promise<Array<tools.AgentModeSummary>>;

export function ListWorkspaceDirectory(arg1:string,arg2:string):Promise<services.WorkspaceDirectory>;

export function LoadChatSession(arg1:string):Promise<services.ChatSession>;

export function LoadDebugScopes(arg1:string,arg2:services.DebugScopesRequest):Promise<services.DebugScopesResponse>;

export function LoadDebugStackTrace(arg1:string,arg2:services.DebugStackTraceRequest):Promise<services.DebugStackTraceResponse>;

export function LoadDebugState(arg1:string):Promise<services.DebugState>;

export function LoadDebugThreads(arg1:string,arg2:services.DebugThreadsRequest):Promise<services.DebugThreadsResponse>;

export function LoadDebugVariables(arg1:string,arg2:services.DebugVariablesRequest):Promise<services.DebugVariablesResponse>;

export function LoadKanbanBoard(arg1:string):Promise<services.KanbanBoard>;

export function LoadRuntimeStatus():Promise<services.RuntimeStatus>;

export function LoadState():Promise<services.AppState>;

export function LoadTaskBoard(arg1:string):Promise<services.TaskBoard>;

export function LoadWebAccessStatus():Promise<services.WebAccessStatus>;

export function LoadWorkspaceChangeReview(arg1:string):Promise<services.WorkspaceChangeReview>;

export function LoadWorkspaceDebugSettings(arg1:string):Promise<services.WorkspaceDebugSettings>;

export function LoadWorkspaceGitChanges(arg1:string):Promise<services.WorkspaceGitChangeReview>;

export function LoadWorkspaceGitCommit(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitCommitDetail>;

export function LoadWorkspaceGitFileDiff(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitChangedFile>;

export function LoadWorkspaceGitFileDiffForScope(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.WorkspaceGitChangedFile>;

export function LoadWorkspaceGitRepository(arg1:string,arg2:string):Promise<services.WorkspaceGitRepositoryView>;

export function LoadWorkspaceGitStash(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitStashDetail>;

export function MergeWorkspaceGitBranch(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function MoveKanbanCard(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function MoveWorkspacePath(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFileEntry>;

export function MoveWorkspaceTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.TaskBoard>;

export function OpenKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function OpenWorkspaceExplorer(arg1:string):Promise<void>;

export function OpenWorkspacePathExplorer(arg1:string,arg2:string):Promise<void>;

export function PauseDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function PrepareRebuildAndRelaunch(arg1:string):Promise<void>;

export function PrepareWorkspaceSymbolRename(arg1:string,arg2:services.WorkspaceDefinitionRequest):Promise<services.WorkspacePrepareRenameResponse>;

export function PruneChatMessage(arg1:string,arg2:string):Promise<services.ChatSession>;

export function ReadExternalTextFile(arg1:string):Promise<services.WorkspaceFile>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<services.WorkspaceFile>;

export function ReadWorkspaceMediaFile(arg1:string,arg2:string):Promise<services.WorkspaceMediaFile>;

export function RecordTokenUsage(arg1:string,arg2:number):Promise<number>;

export function RemoveWorkspaceFolder(arg1:string,arg2:string):Promise<services.AppState>;

export function RenameWorkspacePath(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFileEntry>;

export function RenameWorkspaceSymbol(arg1:string,arg2:services.WorkspaceRenameRequest):Promise<services.WorkspaceRenameResponse>;

export function ReorderWorkspaceTasks(arg1:string,arg2:Array<string>,arg3:string):Promise<services.TaskBoard>;

export function ReorderWorkspaces(arg1:Array<string>):Promise<services.AppState>;

export function ReplayWorkspaceSymbolRename(arg1:string,arg2:services.WorkspaceRenameReplayRequest):Promise<services.WorkspaceRenameReplayResponse>;

export function ResetKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function ResetTokenBudget(arg1:string):Promise<void>;

export function ResolveMode(arg1:string):Promise<tools.AgentModeSummary>;

export function ResolveModeProvider(arg1:string):Promise<tools.AgentModeSummary>;

export function ResolveWorkspaceTextFilePath(arg1:string,arg2:string):Promise<string>;

export function RetryChatMessage(arg1:string,arg2:string,arg3:string):Promise<services.ChatSession>;

export function RotateWebAccessToken():Promise<services.AppState>;

export function RunWorkspaceGitAction(arg1:string,arg2:string,arg3:services.WorkspaceGitActionRequest):Promise<services.WorkspaceGitRepositoryView>;

export function SaveDashboardLayout(arg1:string,arg2:Array<services.DashboardWidgetJSON>):Promise<void>;

export function SaveExternalTextFile(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFile>;

export function SaveSettings(arg1:llm.Settings):Promise<services.AppState>;

export function SaveWebAccessSettings(arg1:services.WebAccessSettings):Promise<services.AppState>;

export function SaveWorkspaceDebugSettings(arg1:string,arg2:services.WorkspaceDebugSettingsInput):Promise<services.WorkspaceDebugSettings>;

export function SaveWorkspaceFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.WorkspaceFile>;

export function SaveWorkspaceFileAs(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceFile>;

export function SearchWorkspaceFiles(arg1:string,arg2:string,arg3:boolean):Promise<services.WorkspaceFileSearchResult>;

export function SearchWorkspaceText(arg1:string,arg2:services.WorkspaceTextSearchRequest):Promise<services.WorkspaceTextSearchResult>;

export function SendChatMessage(arg1:string,arg2:string):Promise<services.ChatSession>;

export function SendChatMessageWithAttachments(arg1:string,arg2:services.ChatMessageRequest):Promise<services.ChatSession>;

export function SendChatMessageWithPlanMode(arg1:string,arg2:string,arg3:boolean):Promise<services.ChatSession>;

export function SetActiveWorkspace(arg1:string):Promise<services.AppState>;

export function SetDebugBreakpoints(arg1:string,arg2:services.DebugSetBreakpointsRequest):Promise<services.DebugState>;

export function SetLivenessConfig(arg1:string,arg2:services.LivenessConfig):Promise<void>;

export function SetTokenBudget(arg1:string,arg2:number):Promise<void>;

export function SetWorkspaceBuildCommand(arg1:string,arg2:string):Promise<services.AppState>;

export function SetWorkspaceDefaultPlanMode(arg1:string,arg2:boolean):Promise<services.AppState>;

export function SetWorkspaceFolderUseAgents(arg1:string,arg2:string,arg3:boolean):Promise<services.AppState>;

export function SetWorkspaceIconFromPath(arg1:string,arg2:string):Promise<services.AppState>;

export function SetWorkspaceIconFromUpload(arg1:string,arg2:services.WorkspaceIconInput):Promise<services.AppState>;

export function SetWorkspaceLetter(arg1:string,arg2:string):Promise<services.AppState>;

export function SetWorkspaceSearchParentGitRepositories(arg1:string,arg2:boolean):Promise<services.AppState>;

export function SetWorkspaceSelectedDebugConfiguration(arg1:string,arg2:string):Promise<services.WorkspaceDebugSettings>;

export function SetWorkspaceTaskCompleted(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<services.TaskBoard>;

export function Shutdown():Promise<void>;

export function StageWorkspaceGitChanges(arg1:string,arg2:string):Promise<services.WorkspaceGitRepositoryView>;

export function StageWorkspaceGitFile(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function StartDebugSession(arg1:string,arg2:services.DebugStartRequest):Promise<services.DebugState>;

export function StartHeartbeat(arg1:string,arg2:services.HeartbeatConfig):Promise<void>;

export function StartKanbanExecution(arg1:string,arg2:number):Promise<services.KanbanBoard>;

export function StartKanbanExecutionWithContext(arg1:context.Context,arg2:string,arg3:number):Promise<void>;

export function StartWatchdog(arg1:string,arg2:services.WatchdogConfig):Promise<void>;

export function StepIntoDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function StepOutDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function StepOverDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function StopChatStream(arg1:string):Promise<services.ChatSession>;

export function StopDebugSession(arg1:string,arg2:services.DebugSessionRequest):Promise<services.DebugState>;

export function StopHeartbeat(arg1:string):Promise<void>;

export function StopKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function StopKanbanExecution(arg1:string):Promise<services.KanbanBoard>;

export function StopWatchdog(arg1:string):Promise<void>;

export function SubmitInlineCodePrompt(arg1:string,arg2:services.InlineCodePromptRequest):Promise<services.InlineCodePromptResponse>;

export function SwitchWorkspaceGitBranch(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function SyncWorkspaceGitBranch(arg1:string,arg2:string):Promise<services.WorkspaceGitRepositoryView>;

export function UnstageWorkspaceGitChanges(arg1:string,arg2:string):Promise<services.WorkspaceGitRepositoryView>;

export function UnstageWorkspaceGitFile(arg1:string,arg2:string,arg3:string):Promise<services.WorkspaceGitRepositoryView>;

export function UpdateAgentMode(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<string>):Promise<Array<services.AgentMode>>;

export function UpdateAgentModePerTool(arg1:string,arg2:string,arg3:string,arg4:Record<string, Array<string>>):Promise<Array<services.AgentMode>>;

export function UpdateKanbanCardDescription(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function UpdateKanbanCardDirection(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function UpdateWorkspaceTask(arg1:string,arg2:string,arg3:services.TaskInput,arg4:string):Promise<services.TaskBoard>;

export function WorkspaceIconHandler():Promise<http.Handler>;

export function WorkspaceIconMiddleware(arg1:http.Handler):Promise<http.Handler>;
