// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKanbanCardMessage(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['AddKanbanCardMessage'](arg1, arg2, arg3);
}

export function AddWorkspace(arg1) {
  return window['go']['services']['SystemService']['AddWorkspace'](arg1);
}

export function AppInfo() {
  return window['go']['services']['SystemService']['AppInfo']();
}

export function ChooseWorkspaceFolder() {
  return window['go']['services']['SystemService']['ChooseWorkspaceFolder']();
}

export function ChooseWorkspaceIcon(arg1) {
  return window['go']['services']['SystemService']['ChooseWorkspaceIcon'](arg1);
}

export function ClearChat(arg1) {
  return window['go']['services']['SystemService']['ClearChat'](arg1);
}

export function ClearDoneKanbanCards(arg1) {
  return window['go']['services']['SystemService']['ClearDoneKanbanCards'](arg1);
}

export function ClearWorkspaceChangeReview(arg1) {
  return window['go']['services']['SystemService']['ClearWorkspaceChangeReview'](arg1);
}

export function ClearWorkspaceIcon(arg1) {
  return window['go']['services']['SystemService']['ClearWorkspaceIcon'](arg1);
}

export function CloseKanbanCardDetail(arg1, arg2) {
  return window['go']['services']['SystemService']['CloseKanbanCardDetail'](arg1, arg2);
}

export function CompleteWorkspaceFile(arg1, arg2) {
  return window['go']['services']['SystemService']['CompleteWorkspaceFile'](arg1, arg2);
}

export function CreateKanbanCardFromChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['CreateKanbanCardFromChatMessage'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['services']['SystemService']['DeleteWorkspace'](arg1);
}

export function EditChatMessage(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['EditChatMessage'](arg1, arg2, arg3);
}

export function ExecutePlan(arg1) {
  return window['go']['services']['SystemService']['ExecutePlan'](arg1);
}

export function ListWorkspaceDirectory(arg1, arg2) {
  return window['go']['services']['SystemService']['ListWorkspaceDirectory'](arg1, arg2);
}

export function LoadChatSession(arg1) {
  return window['go']['services']['SystemService']['LoadChatSession'](arg1);
}

export function LoadKanbanBoard(arg1) {
  return window['go']['services']['SystemService']['LoadKanbanBoard'](arg1);
}

export function LoadState() {
  return window['go']['services']['SystemService']['LoadState']();
}

export function LoadWorkspaceChangeReview(arg1) {
  return window['go']['services']['SystemService']['LoadWorkspaceChangeReview'](arg1);
}

export function LoadWorkspaceGitChanges(arg1) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitChanges'](arg1);
}

export function MoveKanbanCard(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['MoveKanbanCard'](arg1, arg2, arg3);
}

export function OpenKanbanCardDetail(arg1, arg2) {
  return window['go']['services']['SystemService']['OpenKanbanCardDetail'](arg1, arg2);
}

export function OpenWorkspaceExplorer(arg1) {
  return window['go']['services']['SystemService']['OpenWorkspaceExplorer'](arg1);
}

export function OpenWorkspacePathExplorer(arg1, arg2) {
  return window['go']['services']['SystemService']['OpenWorkspacePathExplorer'](arg1, arg2);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['services']['SystemService']['ReadWorkspaceFile'](arg1, arg2);
}

export function ResetKanbanCard(arg1, arg2) {
  return window['go']['services']['SystemService']['ResetKanbanCard'](arg1, arg2);
}

export function ResolveWorkspaceTextFilePath(arg1, arg2) {
  return window['go']['services']['SystemService']['ResolveWorkspaceTextFilePath'](arg1, arg2);
}

export function RetryChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['RetryChatMessage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['services']['SystemService']['SaveSettings'](arg1);
}

export function SaveWorkspaceFile(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['SaveWorkspaceFile'](arg1, arg2, arg3, arg4);
}

export function SearchWorkspaceFiles(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SearchWorkspaceFiles'](arg1, arg2, arg3);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['SendChatMessage'](arg1, arg2);
}

export function SendChatMessageWithAttachments(arg1, arg2) {
  return window['go']['services']['SystemService']['SendChatMessageWithAttachments'](arg1, arg2);
}

export function SendChatMessageWithPlanMode(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SendChatMessageWithPlanMode'](arg1, arg2, arg3);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['services']['SystemService']['SetActiveWorkspace'](arg1);
}

export function SetWorkspaceLetter(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceLetter'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['services']['SystemService']['Shutdown']();
}

export function StartKanbanExecution(arg1, arg2) {
  return window['go']['services']['SystemService']['StartKanbanExecution'](arg1, arg2);
}

export function StopChatStream(arg1) {
  return window['go']['services']['SystemService']['StopChatStream'](arg1);
}

export function StopKanbanCard(arg1, arg2) {
  return window['go']['services']['SystemService']['StopKanbanCard'](arg1, arg2);
}

export function StopKanbanExecution(arg1) {
  return window['go']['services']['SystemService']['StopKanbanExecution'](arg1);
}

export function SubmitInlineCodePrompt(arg1, arg2) {
  return window['go']['services']['SystemService']['SubmitInlineCodePrompt'](arg1, arg2);
}

export function UpdateKanbanCardDescription(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['UpdateKanbanCardDescription'](arg1, arg2, arg3);
}

export function WorkspaceIconHandler() {
  return window['go']['services']['SystemService']['WorkspaceIconHandler']();
}

export function WorkspaceIconMiddleware(arg1) {
  return window['go']['services']['SystemService']['WorkspaceIconMiddleware'](arg1);
}
