// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKanbanCardMessage(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['AddKanbanCardMessage'](arg1, arg2, arg3);
}

export function AddWorkspace(arg1) {
  return window['go']['services']['SystemService']['AddWorkspace'](arg1);
}

export function AddWorkspaceFolder(arg1, arg2) {
  return window['go']['services']['SystemService']['AddWorkspaceFolder'](arg1, arg2);
}

export function AppInfo() {
  return window['go']['services']['SystemService']['AppInfo']();
}

export function CheckTokenBudget(arg1) {
  return window['go']['services']['SystemService']['CheckTokenBudget'](arg1);
}

export function ChooseWorkspaceFileSavePath(arg1, arg2) {
  return window['go']['services']['SystemService']['ChooseWorkspaceFileSavePath'](arg1, arg2);
}

export function ChooseWorkspaceFolder() {
  return window['go']['services']['SystemService']['ChooseWorkspaceFolder']();
}

export function ChooseWorkspaceFolderForWorkspace(arg1) {
  return window['go']['services']['SystemService']['ChooseWorkspaceFolderForWorkspace'](arg1);
}

export function ChooseWorkspaceGitCloneParent() {
  return window['go']['services']['SystemService']['ChooseWorkspaceGitCloneParent']();
}

export function ChooseWorkspaceIcon(arg1) {
  return window['go']['services']['SystemService']['ChooseWorkspaceIcon'](arg1);
}

export function ClearChat(arg1) {
  return window['go']['services']['SystemService']['ClearChat'](arg1);
}

export function ClearDoneKanbanCards(arg1) {
  return window['go']['services']['SystemService']['ClearDoneKanbanCards'](arg1);
}

export function ClearKanbanCardRecovery(arg1, arg2) {
  return window['go']['services']['SystemService']['ClearKanbanCardRecovery'](arg1, arg2);
}

export function ClearWorkspaceChangeReview(arg1) {
  return window['go']['services']['SystemService']['ClearWorkspaceChangeReview'](arg1);
}

export function ClearWorkspaceIcon(arg1) {
  return window['go']['services']['SystemService']['ClearWorkspaceIcon'](arg1);
}

export function CloneWorkspaceGitRepository(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['CloneWorkspaceGitRepository'](arg1, arg2, arg3, arg4);
}

export function CloseKanbanCardDetail(arg1, arg2) {
  return window['go']['services']['SystemService']['CloseKanbanCardDetail'](arg1, arg2);
}

export function CommitWorkspaceGitChanges(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CommitWorkspaceGitChanges'](arg1, arg2, arg3);
}

export function CompleteWorkspaceFile(arg1, arg2) {
  return window['go']['services']['SystemService']['CompleteWorkspaceFile'](arg1, arg2);
}

export function ContinueDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['ContinueDebugSession'](arg1, arg2);
}

export function CreateAgentMode(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['CreateAgentMode'](arg1, arg2, arg3, arg4);
}

export function CreateAgentModeFromChat(arg1) {
  return window['go']['services']['SystemService']['CreateAgentModeFromChat'](arg1);
}

export function CreateAgentModeFromChatProvider(arg1) {
  return window['go']['services']['SystemService']['CreateAgentModeFromChatProvider'](arg1);
}

export function CreateAgentModePerTool(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CreateAgentModePerTool'](arg1, arg2, arg3);
}

export function CreateKanbanCardFromChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['CreateKanbanCardFromChatMessage'](arg1, arg2);
}

export function CreateKanbanCardFromTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['SystemService']['CreateKanbanCardFromTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateKanbanCardsFromEpic(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CreateKanbanCardsFromEpic'](arg1, arg2, arg3);
}

export function CreateMode(arg1, arg2) {
  return window['go']['services']['SystemService']['CreateMode'](arg1, arg2);
}

export function CreateModePerTool(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['CreateModePerTool'](arg1, arg2, arg3, arg4);
}

export function CreateReadyKanbanCard(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['CreateReadyKanbanCard'](arg1, arg2, arg3, arg4);
}

export function CreateSkillFromChat(arg1) {
  return window['go']['services']['SystemService']['CreateSkillFromChat'](arg1);
}

export function CreateWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CreateWorkspaceFile'](arg1, arg2, arg3);
}

export function CreateWorkspaceFolder(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CreateWorkspaceFolder'](arg1, arg2, arg3);
}

export function CreateWorkspaceGitBranch(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['CreateWorkspaceGitBranch'](arg1, arg2, arg3);
}

export function CreateWorkspaceTask(arg1, arg2) {
  return window['go']['services']['SystemService']['CreateWorkspaceTask'](arg1, arg2);
}

export function DeleteAgentMode(arg1) {
  return window['go']['services']['SystemService']['DeleteAgentMode'](arg1);
}

export function DeleteKanbanCard(arg1, arg2) {
  return window['go']['services']['SystemService']['DeleteKanbanCard'](arg1, arg2);
}

export function DeleteSavedCommand(arg1, arg2) {
  return window['go']['services']['SystemService']['DeleteSavedCommand'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['services']['SystemService']['DeleteWorkspace'](arg1);
}

export function DeleteWorkspacePaths(arg1, arg2) {
  return window['go']['services']['SystemService']['DeleteWorkspacePaths'](arg1, arg2);
}

export function DeleteWorkspaceTask(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['DeleteWorkspaceTask'](arg1, arg2, arg3);
}

export function DiscardWorkspaceGitChanges(arg1, arg2) {
  return window['go']['services']['SystemService']['DiscardWorkspaceGitChanges'](arg1, arg2);
}

export function DiscardWorkspaceGitFile(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['DiscardWorkspaceGitFile'](arg1, arg2, arg3);
}

export function EditChatMessage(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['EditChatMessage'](arg1, arg2, arg3, arg4);
}

export function EnforceLiveness(arg1, arg2) {
  return window['go']['services']['SystemService']['EnforceLiveness'](arg1, arg2);
}

export function EvaluateDebugExpression(arg1, arg2) {
  return window['go']['services']['SystemService']['EvaluateDebugExpression'](arg1, arg2);
}

export function ExecutePlan(arg1) {
  return window['go']['services']['SystemService']['ExecutePlan'](arg1);
}

export function FindWorkspaceFileDefinition(arg1, arg2) {
  return window['go']['services']['SystemService']['FindWorkspaceFileDefinition'](arg1, arg2);
}

export function FindWorkspaceFileImplementations(arg1, arg2) {
  return window['go']['services']['SystemService']['FindWorkspaceFileImplementations'](arg1, arg2);
}

export function FindWorkspaceFileReferences(arg1, arg2) {
  return window['go']['services']['SystemService']['FindWorkspaceFileReferences'](arg1, arg2);
}

export function GetDashboardLayouts() {
  return window['go']['services']['SystemService']['GetDashboardLayouts']();
}

export function GetHeartbeatConfig(arg1) {
  return window['go']['services']['SystemService']['GetHeartbeatConfig'](arg1);
}

export function GetLivenessConfig(arg1) {
  return window['go']['services']['SystemService']['GetLivenessConfig'](arg1);
}

export function GetSavedCommands(arg1) {
  return window['go']['services']['SystemService']['GetSavedCommands'](arg1);
}

export function GetTokenBudget(arg1) {
  return window['go']['services']['SystemService']['GetTokenBudget'](arg1);
}

export function GetWatchdogConfig(arg1) {
  return window['go']['services']['SystemService']['GetWatchdogConfig'](arg1);
}

export function GetWorkspaceActivitySummaries() {
  return window['go']['services']['SystemService']['GetWorkspaceActivitySummaries']();
}

export function ListAgentModes(arg1) {
  return window['go']['services']['SystemService']['ListAgentModes'](arg1);
}

export function ListAgentModesProvider() {
  return window['go']['services']['SystemService']['ListAgentModesProvider']();
}

export function ListModes() {
  return window['go']['services']['SystemService']['ListModes']();
}

export function ListWorkspaceDirectory(arg1, arg2) {
  return window['go']['services']['SystemService']['ListWorkspaceDirectory'](arg1, arg2);
}

export function LoadChatSession(arg1) {
  return window['go']['services']['SystemService']['LoadChatSession'](arg1);
}

export function LoadDebugScopes(arg1, arg2) {
  return window['go']['services']['SystemService']['LoadDebugScopes'](arg1, arg2);
}

export function LoadDebugStackTrace(arg1, arg2) {
  return window['go']['services']['SystemService']['LoadDebugStackTrace'](arg1, arg2);
}

export function LoadDebugState(arg1) {
  return window['go']['services']['SystemService']['LoadDebugState'](arg1);
}

export function LoadDebugThreads(arg1, arg2) {
  return window['go']['services']['SystemService']['LoadDebugThreads'](arg1, arg2);
}

export function LoadDebugVariables(arg1, arg2) {
  return window['go']['services']['SystemService']['LoadDebugVariables'](arg1, arg2);
}

export function LoadKanbanBoard(arg1) {
  return window['go']['services']['SystemService']['LoadKanbanBoard'](arg1);
}

export function LoadRuntimeStatus() {
  return window['go']['services']['SystemService']['LoadRuntimeStatus']();
}

export function LoadState() {
  return window['go']['services']['SystemService']['LoadState']();
}

export function LoadTaskBoard(arg1) {
  return window['go']['services']['SystemService']['LoadTaskBoard'](arg1);
}

export function LoadWebAccessStatus() {
  return window['go']['services']['SystemService']['LoadWebAccessStatus']();
}

export function LoadWorkspaceChangeReview(arg1) {
  return window['go']['services']['SystemService']['LoadWorkspaceChangeReview'](arg1);
}

export function LoadWorkspaceDebugSettings(arg1) {
  return window['go']['services']['SystemService']['LoadWorkspaceDebugSettings'](arg1);
}

export function LoadWorkspaceGitChanges(arg1) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitChanges'](arg1);
}

export function LoadWorkspaceGitCommit(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitCommit'](arg1, arg2, arg3);
}

export function LoadWorkspaceGitFileDiff(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitFileDiff'](arg1, arg2, arg3);
}

export function LoadWorkspaceGitFileDiffForScope(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitFileDiffForScope'](arg1, arg2, arg3, arg4);
}

export function LoadWorkspaceGitRepository(arg1, arg2) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitRepository'](arg1, arg2);
}

export function LoadWorkspaceGitStash(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['LoadWorkspaceGitStash'](arg1, arg2, arg3);
}

export function MergeWorkspaceGitBranch(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['MergeWorkspaceGitBranch'](arg1, arg2, arg3);
}

export function MoveKanbanCard(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['MoveKanbanCard'](arg1, arg2, arg3);
}

export function MoveWorkspacePath(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['MoveWorkspacePath'](arg1, arg2, arg3);
}

export function MoveWorkspaceTask(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['MoveWorkspaceTask'](arg1, arg2, arg3, arg4);
}

export function OpenKanbanCardDetail(arg1, arg2) {
  return window['go']['services']['SystemService']['OpenKanbanCardDetail'](arg1, arg2);
}

export function OpenWorkspaceExplorer(arg1) {
  return window['go']['services']['SystemService']['OpenWorkspaceExplorer'](arg1);
}

export function OpenWorkspacePathExplorer(arg1, arg2) {
  return window['go']['services']['SystemService']['OpenWorkspacePathExplorer'](arg1, arg2);
}

export function PauseDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['PauseDebugSession'](arg1, arg2);
}

export function PrepareRebuildAndRelaunch(arg1) {
  return window['go']['services']['SystemService']['PrepareRebuildAndRelaunch'](arg1);
}

export function PrepareWorkspaceSymbolRename(arg1, arg2) {
  return window['go']['services']['SystemService']['PrepareWorkspaceSymbolRename'](arg1, arg2);
}

export function PruneChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['PruneChatMessage'](arg1, arg2);
}

export function ReadExternalTextFile(arg1) {
  return window['go']['services']['SystemService']['ReadExternalTextFile'](arg1);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['services']['SystemService']['ReadWorkspaceFile'](arg1, arg2);
}

export function ReadWorkspaceMediaFile(arg1, arg2) {
  return window['go']['services']['SystemService']['ReadWorkspaceMediaFile'](arg1, arg2);
}

export function RecordTokenUsage(arg1, arg2) {
  return window['go']['services']['SystemService']['RecordTokenUsage'](arg1, arg2);
}

export function RemoveWorkspaceFolder(arg1, arg2) {
  return window['go']['services']['SystemService']['RemoveWorkspaceFolder'](arg1, arg2);
}

export function RenameWorkspacePath(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['RenameWorkspacePath'](arg1, arg2, arg3);
}

export function RenameWorkspaceSymbol(arg1, arg2) {
  return window['go']['services']['SystemService']['RenameWorkspaceSymbol'](arg1, arg2);
}

export function ReorderWorkspaceTasks(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['ReorderWorkspaceTasks'](arg1, arg2, arg3);
}

export function ReorderWorkspaces(arg1) {
  return window['go']['services']['SystemService']['ReorderWorkspaces'](arg1);
}

export function ReplayWorkspaceSymbolRename(arg1, arg2) {
  return window['go']['services']['SystemService']['ReplayWorkspaceSymbolRename'](arg1, arg2);
}

export function ResetKanbanCard(arg1, arg2) {
  return window['go']['services']['SystemService']['ResetKanbanCard'](arg1, arg2);
}

export function ResetTokenBudget(arg1) {
  return window['go']['services']['SystemService']['ResetTokenBudget'](arg1);
}

export function ResolveMode(arg1) {
  return window['go']['services']['SystemService']['ResolveMode'](arg1);
}

export function ResolveModeProvider(arg1) {
  return window['go']['services']['SystemService']['ResolveModeProvider'](arg1);
}

export function ResolveWorkspaceTextFilePath(arg1, arg2) {
  return window['go']['services']['SystemService']['ResolveWorkspaceTextFilePath'](arg1, arg2);
}

export function RetryChatMessage(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['RetryChatMessage'](arg1, arg2, arg3);
}

export function RotateWebAccessToken() {
  return window['go']['services']['SystemService']['RotateWebAccessToken']();
}

export function RunShellCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['SystemService']['RunShellCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function RunWorkspaceGitAction(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['RunWorkspaceGitAction'](arg1, arg2, arg3);
}

export function SaveChatImageToDisk(arg1, arg2) {
  return window['go']['services']['SystemService']['SaveChatImageToDisk'](arg1, arg2);
}

export function SaveDashboardLayout(arg1, arg2) {
  return window['go']['services']['SystemService']['SaveDashboardLayout'](arg1, arg2);
}

export function SaveExternalTextFile(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SaveExternalTextFile'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['services']['SystemService']['SaveSettings'](arg1);
}

export function SaveWebAccessSettings(arg1) {
  return window['go']['services']['SystemService']['SaveWebAccessSettings'](arg1);
}

export function SaveWorkspaceDebugSettings(arg1, arg2) {
  return window['go']['services']['SystemService']['SaveWorkspaceDebugSettings'](arg1, arg2);
}

export function SaveWorkspaceFile(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['SaveWorkspaceFile'](arg1, arg2, arg3, arg4);
}

export function SaveWorkspaceFileAs(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SaveWorkspaceFileAs'](arg1, arg2, arg3);
}

export function SearchWorkspaceFiles(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SearchWorkspaceFiles'](arg1, arg2, arg3);
}

export function SearchWorkspaceText(arg1, arg2) {
  return window['go']['services']['SystemService']['SearchWorkspaceText'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['services']['SystemService']['SendChatMessage'](arg1, arg2);
}

export function SendChatMessageWithAttachments(arg1, arg2) {
  return window['go']['services']['SystemService']['SendChatMessageWithAttachments'](arg1, arg2);
}

export function SendChatMessageWithPlanMode(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SendChatMessageWithPlanMode'](arg1, arg2, arg3);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['services']['SystemService']['SetActiveWorkspace'](arg1);
}

export function SetDebugBreakpoints(arg1, arg2) {
  return window['go']['services']['SystemService']['SetDebugBreakpoints'](arg1, arg2);
}

export function SetLivenessConfig(arg1, arg2) {
  return window['go']['services']['SystemService']['SetLivenessConfig'](arg1, arg2);
}

export function SetTokenBudget(arg1, arg2) {
  return window['go']['services']['SystemService']['SetTokenBudget'](arg1, arg2);
}

export function SetWorkspaceBuildCommand(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceBuildCommand'](arg1, arg2);
}

export function SetWorkspaceDefaultPlanMode(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceDefaultPlanMode'](arg1, arg2);
}

export function SetWorkspaceFolderUseAgents(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SetWorkspaceFolderUseAgents'](arg1, arg2, arg3);
}

export function SetWorkspaceIconFromPath(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceIconFromPath'](arg1, arg2);
}

export function SetWorkspaceIconFromUpload(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceIconFromUpload'](arg1, arg2);
}

export function SetWorkspaceLetter(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceLetter'](arg1, arg2);
}

export function SetWorkspaceSearchParentGitRepositories(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceSearchParentGitRepositories'](arg1, arg2);
}

export function SetWorkspaceSelectedDebugConfiguration(arg1, arg2) {
  return window['go']['services']['SystemService']['SetWorkspaceSelectedDebugConfiguration'](arg1, arg2);
}

export function SetWorkspaceTaskCompleted(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['SetWorkspaceTaskCompleted'](arg1, arg2, arg3, arg4);
}

export function Shutdown() {
  return window['go']['services']['SystemService']['Shutdown']();
}

export function StageWorkspaceGitChanges(arg1, arg2) {
  return window['go']['services']['SystemService']['StageWorkspaceGitChanges'](arg1, arg2);
}

export function StageWorkspaceGitFile(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['StageWorkspaceGitFile'](arg1, arg2, arg3);
}

export function StartDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['StartDebugSession'](arg1, arg2);
}

export function StartHeartbeat(arg1, arg2) {
  return window['go']['services']['SystemService']['StartHeartbeat'](arg1, arg2);
}

export function StartKanbanExecution(arg1, arg2) {
  return window['go']['services']['SystemService']['StartKanbanExecution'](arg1, arg2);
}

export function StartKanbanExecutionWithContext(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['StartKanbanExecutionWithContext'](arg1, arg2, arg3);
}

export function StartWatchdog(arg1, arg2) {
  return window['go']['services']['SystemService']['StartWatchdog'](arg1, arg2);
}

export function StepIntoDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['StepIntoDebugSession'](arg1, arg2);
}

export function StepOutDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['StepOutDebugSession'](arg1, arg2);
}

export function StepOverDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['StepOverDebugSession'](arg1, arg2);
}

export function StopChatStream(arg1) {
  return window['go']['services']['SystemService']['StopChatStream'](arg1);
}

export function StopDebugSession(arg1, arg2) {
  return window['go']['services']['SystemService']['StopDebugSession'](arg1, arg2);
}

export function StopHeartbeat(arg1) {
  return window['go']['services']['SystemService']['StopHeartbeat'](arg1);
}

export function StopKanbanCard(arg1, arg2) {
  return window['go']['services']['SystemService']['StopKanbanCard'](arg1, arg2);
}

export function StopKanbanExecution(arg1) {
  return window['go']['services']['SystemService']['StopKanbanExecution'](arg1);
}

export function StopShellCommand(arg1, arg2) {
  return window['go']['services']['SystemService']['StopShellCommand'](arg1, arg2);
}

export function StopWatchdog(arg1) {
  return window['go']['services']['SystemService']['StopWatchdog'](arg1);
}

export function SubmitInlineCodePrompt(arg1, arg2) {
  return window['go']['services']['SystemService']['SubmitInlineCodePrompt'](arg1, arg2);
}

export function SwitchWorkspaceGitBranch(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['SwitchWorkspaceGitBranch'](arg1, arg2, arg3);
}

export function SyncWorkspaceGitBranch(arg1, arg2) {
  return window['go']['services']['SystemService']['SyncWorkspaceGitBranch'](arg1, arg2);
}

export function UnstageWorkspaceGitChanges(arg1, arg2) {
  return window['go']['services']['SystemService']['UnstageWorkspaceGitChanges'](arg1, arg2);
}

export function UnstageWorkspaceGitFile(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['UnstageWorkspaceGitFile'](arg1, arg2, arg3);
}

export function UpdateAgentMode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['SystemService']['UpdateAgentMode'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateAgentModePerTool(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['UpdateAgentModePerTool'](arg1, arg2, arg3, arg4);
}

export function UpdateKanbanCardDescription(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['UpdateKanbanCardDescription'](arg1, arg2, arg3);
}

export function UpdateKanbanCardDirection(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['UpdateKanbanCardDirection'](arg1, arg2, arg3);
}

export function UpdateWorkspaceTask(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['UpdateWorkspaceTask'](arg1, arg2, arg3, arg4);
}

export function UpsertSavedCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['SystemService']['UpsertSavedCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function WorkspaceIconHandler() {
  return window['go']['services']['SystemService']['WorkspaceIconHandler']();
}

export function WorkspaceIconMiddleware(arg1) {
  return window['go']['services']['SystemService']['WorkspaceIconMiddleware'](arg1);
}
