// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {llm} from '../models';

export function AddKanbanCardMessage(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function AddWorkspace(arg1:string):Promise<services.AppState>;

export function AppInfo():Promise<services.AppInfo>;

export function ChooseWorkspaceFolder():Promise<services.AppState>;

export function ClearChat(arg1:string):Promise<services.ChatSession>;

export function CloseKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function DeleteWorkspace(arg1:string):Promise<services.AppState>;

export function ExecutePlan(arg1:string):Promise<services.KanbanBoard>;

export function ListWorkspaceDirectory(arg1:string,arg2:string):Promise<services.WorkspaceDirectory>;

export function LoadChatSession(arg1:string):Promise<services.ChatSession>;

export function LoadKanbanBoard(arg1:string):Promise<services.KanbanBoard>;

export function LoadState():Promise<services.AppState>;

export function MoveKanbanCard(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function OpenKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<services.WorkspaceFile>;

export function ResetKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function ResolveWorkspaceTextFilePath(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:llm.Settings):Promise<services.AppState>;

export function SaveWorkspaceFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.WorkspaceFile>;

export function SearchWorkspaceFiles(arg1:string,arg2:string,arg3:boolean):Promise<services.WorkspaceFileSearchResult>;

export function SendChatMessage(arg1:string,arg2:string):Promise<services.ChatSession>;

export function SetActiveWorkspace(arg1:string):Promise<services.AppState>;

export function SetWorkspaceLetter(arg1:string,arg2:string):Promise<services.AppState>;

export function Shutdown():Promise<void>;

export function StartKanbanExecution(arg1:string,arg2:number):Promise<services.KanbanBoard>;

export function StopChatStream(arg1:string):Promise<services.ChatSession>;

export function StopKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function StopKanbanExecution(arg1:string):Promise<services.KanbanBoard>;

export function SubmitInlineCodePrompt(arg1:string,arg2:services.InlineCodePromptRequest):Promise<services.InlineCodePromptResponse>;
