// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {llm} from '../models';
import {http} from '../models';

export function AddKanbanCardMessage(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function AddWorkspace(arg1:string):Promise<services.AppState>;

export function AddWorkspaceFolder(arg1:string,arg2:string):Promise<services.AppState>;

export function AppInfo():Promise<services.AppInfo>;

export function ChooseWorkspaceFolder():Promise<services.AppState>;

export function ChooseWorkspaceFolderForWorkspace(arg1:string):Promise<services.AppState>;

export function ChooseWorkspaceIcon(arg1:string):Promise<services.AppState>;

export function ClearChat(arg1:string):Promise<services.ChatSession>;

export function ClearDoneKanbanCards(arg1:string):Promise<services.KanbanBoard>;

export function ClearWorkspaceChangeReview(arg1:string):Promise<services.WorkspaceChangeReview>;

export function ClearWorkspaceIcon(arg1:string):Promise<services.AppState>;

export function CloseKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function CompleteWorkspaceFile(arg1:string,arg2:services.WorkspaceCompletionRequest):Promise<services.WorkspaceCompletionResponse>;

export function CreateKanbanCardFromChatMessage(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function DeleteWorkspace(arg1:string):Promise<services.AppState>;

export function EditChatMessage(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<services.ChatSession>;

export function ExecutePlan(arg1:string):Promise<services.KanbanBoard>;

export function FindWorkspaceFileDefinition(arg1:string,arg2:services.WorkspaceDefinitionRequest):Promise<services.WorkspaceDefinitionResponse>;

export function ListWorkspaceDirectory(arg1:string,arg2:string):Promise<services.WorkspaceDirectory>;

export function LoadChatSession(arg1:string):Promise<services.ChatSession>;

export function LoadKanbanBoard(arg1:string):Promise<services.KanbanBoard>;

export function LoadState():Promise<services.AppState>;

export function LoadWorkspaceChangeReview(arg1:string):Promise<services.WorkspaceChangeReview>;

export function LoadWorkspaceGitChanges(arg1:string):Promise<services.WorkspaceGitChangeReview>;

export function MoveKanbanCard(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function OpenKanbanCardDetail(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function OpenWorkspaceExplorer(arg1:string):Promise<void>;

export function OpenWorkspacePathExplorer(arg1:string,arg2:string):Promise<void>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<services.WorkspaceFile>;

export function RemoveWorkspaceFolder(arg1:string,arg2:string):Promise<services.AppState>;

export function ResetKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function ResolveWorkspaceTextFilePath(arg1:string,arg2:string):Promise<string>;

export function RetryChatMessage(arg1:string,arg2:string,arg3:boolean):Promise<services.ChatSession>;

export function SaveSettings(arg1:llm.Settings):Promise<services.AppState>;

export function SaveWorkspaceFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<services.WorkspaceFile>;

export function SearchWorkspaceFiles(arg1:string,arg2:string,arg3:boolean):Promise<services.WorkspaceFileSearchResult>;

export function SendChatMessage(arg1:string,arg2:string):Promise<services.ChatSession>;

export function SendChatMessageWithAttachments(arg1:string,arg2:services.ChatMessageRequest):Promise<services.ChatSession>;

export function SendChatMessageWithPlanMode(arg1:string,arg2:string,arg3:boolean):Promise<services.ChatSession>;

export function SetActiveWorkspace(arg1:string):Promise<services.AppState>;

export function SetWorkspaceFolderUseAgents(arg1:string,arg2:string,arg3:boolean):Promise<services.AppState>;

export function SetWorkspaceLetter(arg1:string,arg2:string):Promise<services.AppState>;

export function Shutdown():Promise<void>;

export function StartKanbanExecution(arg1:string,arg2:number):Promise<services.KanbanBoard>;

export function StopChatStream(arg1:string):Promise<services.ChatSession>;

export function StopKanbanCard(arg1:string,arg2:string):Promise<services.KanbanBoard>;

export function StopKanbanExecution(arg1:string):Promise<services.KanbanBoard>;

export function SubmitInlineCodePrompt(arg1:string,arg2:services.InlineCodePromptRequest):Promise<services.InlineCodePromptResponse>;

export function UpdateKanbanCardDescription(arg1:string,arg2:string,arg3:string):Promise<services.KanbanBoard>;

export function WorkspaceIconHandler():Promise<http.Handler>;

export function WorkspaceIconMiddleware(arg1:http.Handler):Promise<http.Handler>;
